### ISSUE TITLE
attendanceDatewise doesnt work

### ISSUE THREAD

**Issue by himohitj** [cro2003/lnctApi#1]
![Screenshot 2023-10-15 210718](https://github.com/cro2003/lnctApi/assets/124264130/0a460715-7561-4c73-b6fd-19edf3861240)

looks like there is a change in the site please refer to above image

**Comment by cro2003** [comment]
Yes after new Updations in Accsoft in Table it's not working, I will try to fix as soon as i get time.

**Comment by cro2003** [comment]
Fixed the Bug for more Deatils refer [1bb6800](https://github.com/cro2003/lnctApi/commit/1bb680031e6ee166dba7b56326352bc4ac271f2e)
